apiVersion: v2
name: chart
description: A Helm chart for my movie-watchlist app
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: "12.1.6"
    repository: "https://charts.bitnami.com/bitnami"